improve

diff --git a/.github/workflows/check-build.yml b/.github/workflows/check-build.yml
--- a/.github/workflows/check-build.yml
+++ b/.github/workflows/check-build.yml
@@ -33,7 +33,8 @@ jobs:
           python -m pip install --upgrade pip
           pip install -r 'scripts/knowledgebase-checker/requirements.txt'
 
-      - name: Run spellcheck
+      - name: Run checks
+        id: check_step
         run: |
           if matrix.check_type == 'spellcheck'; then
             ./scripts/check-doc-aspell
@@ -44,6 +45,9 @@ jobs:
           fi
           
           if [[ $exit_code -ne 0]]; then
-            echo "::error::${{matrix.check_type}}" check failed. See logs for details."
-            exit $exit_code
+            echo "::error::${{ matrix.check_type }}" check failed. See logs for details."
           fi
+
+      - name: Check outcome
+        if: steps.check_step.outcome == 'failure'
+        run: exit 1
