send yarn build log to file and check

diff --git a/.github/workflows/test-pr-build.yml b/.github/workflows/test-pr-build.yml
--- a/.github/workflows/test-pr-build.yml
+++ b/.github/workflows/test-pr-build.yml
@@ -45,5 +45,6 @@ jobs:
           yarn install --frozen-lockfile
 
       - name: Test build website
-        run: yarn build
-
+        run:  |
+          yarn build 2>&1 | tee -a yarnbuild.out
+          if grep -q Error yarnbuild.out; then { echo "Error in output" ; exit 1; } ; fi
